### ISSUE TITLE
Bad positionning with latest ActiveAdmin

### ISSUE THREAD

**Issue by geoffroymontel** [unmantained-activeadmin-plugins/activeadmin-wysihtml5#26]
Hello

I use ActiveAdmin on the master branch with Rails 4.1 and the Wysihtml5 editor is not well positionned
![capture decran 2014-04-23 a 11 10 36](https://cloud.githubusercontent.com/assets/352910/2775596/61d76562-cac7-11e3-966c-f11d75cba8a3.png)

Something like this would fix it

``` css
body.active_admin form .activeadmin-wysihtml5 {
  float: left;
  width: 70%;
}
```

Best regards

Geoffroy
